export * from './src/checkStatus'
export * from './src/fetch'
export * from './src/interface/checkStatus.interface'
export * from './src/interface/fetch.interface'
export * from './src/interface/parseData.interface'
export * from './src/parseData'
